driver/debug.c
driver/driver.c
driver/driver.h
driver/driver_extension.c
driver/driver_extension.h
driver/rbd_protocol.c
driver/rbd_protocol.h
driver/scsi_driver_extensions.c
driver/scsi_function.c
driver/scsi_function.h
driver/scsi_operation.c
driver/userspace.c
driver/userspace.h
driver/userspace_shared.h
driver/util.c
driver/util.h
lib/ksocket_wsk/berkeley.c
lib/ksocket_wsk/berkeley.h
lib/ksocket_wsk/ksocket.c
lib/ksocket_wsk/ksocket.h
userspace/userspace/ioctl.c
userspace/userspace/ioctl.h
userspace/userspace/main.cpp
vstudio/reinstall.ps1

At the moment, we're sending one NBD request at a time and wait for
it to complete. While simple, this is very inefficient.
This change will send the requests as they arrive, using a separate
thread to read the replies from the NBD channel. We'll limit
the maximum number of in-flight requests, using a hard-coded value
of 255 for the time being.

Async requests

---

driver/rbd_protocol.h
driver/scsi_operation.c
driver/userspace.c
driver/userspace.h
driver/userspace_shared.h
driver/util.c
userspace/userspace/ioctl.c
userspace/userspace/ioctl.h
userspace/userspace/main.cpp

This change will allow passing NBD flags. For now, we're only using
the read-only flag. In the future, we'll also detect and use
TRIM support.

Add read-only mode

---

README.md

Our readme sample is configuring the NBD server to use port 9000.
We'll switch to the IANA assigned NBD port, 10809.

nit: Update the readme to use the standard NBD port

---

libwnbd/libwnbd.def

MSVC complains:
https://ci.appveyor.com/project/aserdean/wnbd/branch/master/job/9i0gd0blgdj446vr#L194
```
warning LNK4070: /OUT:wnbd.dll directive in .EXP differs from output filename
```
Change library name from wnbd to libwnd in the DEF file

Update library name in DEF file

---

appveyor.yml
driver/driver.c
driver/driver.h
driver/nbd_protocol.c
driver/nbd_protocol.h
driver/util.c
driver/wnbd_dispatch.c
ksocket_wsk/ksocket_wsk.vcxproj
libwnbd/libwnbd.vcxproj
vstudio/driver.vcxproj
vstudio/wnbd.sln
wnbd-client/wnbd-client.vcxproj

This PR addresses code analysis warnings found in `driver` project.
Adds a new configuration called `Analysis` so the Microsoft code analyzer is ran, with the default rule set, when building the project.
Also update appveyor matrix so we can see potential defects.
A sample output can be viewed here:
https://ci.appveyor.com/project/aserdean/wnbd-1/build/job/f382y7rx6ygidm91#L251

Code analysis

---

appveyor.yml

This patch adds Static Driver Verifier check on the `Release` configuration.
SDV fails to run with `vcvarsx86_amd64`, switch to amd64 only.
---
Appveyor build for reference: (1) https://ci.appveyor.com/project/aserdean/wnbd-1/builds/35228190
(2) https://ci.appveyor.com/project/aserdean/wnbd-1/builds/35228190/job/tedpc6m4yq9ywa9r#L399

appveyor: Run SDV on Analyze configuration

---

.gitignore
driver/userspace.c
include/wnbd.h
include/wnbd_ioctl.h
libwnbd/libwnbd.cpp
libwnbd/libwnbd.def
libwnbd/libwnbd.vcxproj
libwnbd/wnbd_ioctl.c
vstudio/driver.vcxproj
vstudio/generate_version_h.ps1
wnbd-client/cmd.cpp
wnbd-client/cmd.h
wnbd-client/main.cpp
wnbd-client/wnbd-client.vcxproj

We'll use semantic versioning, which will be set through git tags.
For now, a script will be run as a pre-build event, parsing the git
tag and generating version.h.
wnbd-client -v will return the wnbd-client, the libwnbd as well as
the driver version.
We're using the "git describe" short version, which includes the
commit id and offset for untagged commits. If needed, we can easily
add other version info (e.g. build type, architecture, etc).

Add versioning

---

appveyor.yml
vstudio/driver.vcxproj

This patch adds a new build action on the `Analyze` property which will
run SDV. During the SDV process paths are mangled and an extra `\` is needed
when building the `Release` build.
This patch also removes unneeded appveyor step.

Add SDV check as post build action

---

include/wnbd.h
libwnbd/libwnbd.cpp
libwnbd/libwnbd.def
libwnbd/libwnbd.vcxproj
libwnbd/libwnbd.vcxproj.filters
libwnbd/utils.cpp
libwnbd/utils.h
libwnbd/wnbd_ioctl.cpp
libwnbd/wnbd_log.c
libwnbd/wnbd_log.h
libwnbd/wnbd_wmi.cpp
wnbd-client/cmd.cpp
wnbd-client/main.cpp

userspace: update logging
We allow the library consumer to provide a logger function.
This is really convenient because the consumer can choose how those
messages will be handled (e.g. can use ETW or simple file logging,
can format the messages, etc).
The main issue is that the logger is tied to the WNBD_DEVICE
structure, which limits its usefulness since we can't use it
in functions that don't accept this parameter.
This change will add a static logger function pointer, allowing
the consumer to override it using a setter.
This commit also adds log messages to all the functions that couldn't
use logging before.
Depends-On: https://github.com/cloudbase/wnbd/pull/23

userspace: update logging

---

driver/driver.c
driver/nbd_dispatch.c
driver/scsi_operation.c
driver/wnbd_dispatch.c
libwnbd/libwnbd.cpp
libwnbd/wnbd_ioctl.cpp

driver: unmap/flush/FUA support
Those features are already supported by libwnbd and our nbd
client, we'll need to update our IO dispatcher to propagate
them.

driver: unmap/flush/FUA support

---

include/wnbd.h
libwnbd/libwnbd.cpp
libwnbd/libwnbd.def
libwnbd/wnbd_ioctl.cpp
wnbd-client/cmd.cpp

This change fixes deadlocks occurring when communicating with the
WNBD driver using DeviceIoControl[1][2].
We're setting FILE_FLAG_OVERLAPPED when opening the WNBD device
in order to be able to submit multiple requests simultaneously.
The Windows docs state that in this case, an OVERLAPED structure
must be passed to functions such as ReadFile or WriteFile without
explicitly mentioning DeviceIoControl.
Apparently DeviceIoControl can hang if we don't pass an overlapped
structure, especially when having a high number of concurrent
requests. This is likely related to the event wait involved.
We're going to update the libwnbd *Ioctl* functions, adding an
optional LPOVERLAPPED argument. When not provided by the caller,
we're initalizing an internal OVERLAPED structure and wait for
the operation …

Always use an overlapped structure when calling DeviceIoControl

---

.gitignore
README.md
get_dependencies.ps1
libwnbd/libwnbd.vcxproj
packages.config
vstudio/build_deps.vcxproj
vstudio/driver.vcxproj
vstudio/driver.vcxproj.user
vstudio/reinstall.ps1
vstudio/wnbd.sln
wnbd-client/client.cpp
wnbd-client/client.h
wnbd-client/cmd.cpp
wnbd-client/cmd.h
wnbd-client/main.cpp
wnbd-client/usage.cc
wnbd-client/usage.h
wnbd-client/wnbd-client.vcxproj

At the moment, wnbd-client only uses positional arguments. This
is highly inconvenient as we're adding more arguments.
For example, the "wnbd-client map" syntax looks like this:
``wnbd-client map  <InstanceName> <HostName> <PortName> <ExportName>
[<SkipNBDNegotiation> <ReadOnly> <DiskSize> <BlockSize>]``
This change adds named optional arguments as well as a simple
mechanism of defining command options using Boost. This also allows
us to automatically generate better help strings.
While at it, we're adding a "--debug" option and expose soft disconnect
parameters.

wnbd-client: use named arguments and improve help strings

---

driver/scsi_function.c
driver/util.c
driver/wnbd_dispatch.c
libwnbd/wnbd_ioctl.cpp

When hitting timeouts, Storport resets the adapter. NBD replies
don't include the IO size so we keep that information around
when resetting the adapter. We don't need the payload itself,
just the size so that we can tell where the next NBD header
starts.
We don't have to do this for the IOCTL based IO channel, in
which case we're going to clean up the IO queue.

driver: clean up IO queue when resetting adapter

---

driver/options.c

MSVC 2017 complains:
Warning	C4204	nonstandard extension used: non-constant aggregate initializer	driver	driver\options.c	84
Warning	C4204	nonstandard extension used: non-constant aggregate initializer	driver	driver\options.c	153
Warning	C4204	nonstandard extension used: non-constant aggregate initializer	driver	driver\options.c	154
(the above also applies on nonupdated VS 2019)
For reference:
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/6b73z23c(v=vs.90)
Such type of initializations are useful and we disable the warning since it can
be safely ignored.

Fix compilation issues VS 2017

---

include/wnbd.h
include/wnbd_ioctl.h

We're going to add structure size assertions to ensure that we aren't
breaking backwards compatibility by mistake.
This is also helps spotting portability issues as other compilers
might use different structure layouts, especially when having
bitfields.

libwnbd: pin structure sizes

---

wnbd-client/wnbd-client.vcxproj

Running code analysis on wnbd-client project will also include the boost
source code.
This patch disables the static code analysis on the third party libraries
to reduce the verbosity on the build log:
https://ci.appveyor.com/project/aserdean/wnbd/builds/35959630/job/oj6tg32upx01n8j7#L742

Disable static code analysis on wnbd-client project

---

driver/wnbd.rc
include/vendor.h
vstudio/driver.vcxproj
vstudio/driver.vcxproj.filters
vstudio/generate_version_h.ps1

Versioning and other details should be visible through properties on the driver file (through Windows Explorer). As Windows versions commonly use a four digit versioning scheme (x.x.x.x), use the git commit count as the fourth digit.

Add driver properties through resource file

---

vstudio/generate_version_h.ps1

When building the project, we're automatically detecting the WNBD
version using the git tag.
The issue is that we shouldn't rely on it, users might just download
a zip of the archive.
This change will generate a version.h template that the user can fill
when the version detection fails.

Add version detection fallback

---

driver/debug.h
driver/driver.c
driver/nbd_dispatch.c
driver/nbd_protocol.c
driver/options.c
driver/scsi_driver_extensions.c
driver/scsi_function.c
driver/scsi_operation.c
driver/userspace.c
driver/util.c
driver/wnbd_dispatch.c

This PR is intended to clean the wnbd log messages.
- Remove leading `: ` from log messages.
- Fix format specifiers.
- Demote some log messages.
- Print NTSTATUS as hex instead of integer format.
- Remove extraneous arguments passed to log messages

Clean log messages

---

README.md
include/wnbd.h
libwnbd/libwnbd.def
libwnbd/wnbd_ioctl.cpp
vstudio/reinstall.ps1
wnbd-client/client.cpp
wnbd-client/cmd.cpp
wnbd-client/cmd.h

This patch introduces two more supported CLI commands.
`install-driver`, `clean-uninstall`.
The hardware ID and length are predefined, the only required installation
argument is the INF file location.
The clean uninstall sequence will remove any created devices and it will
also try to remove any previous driver installations by  cycling through
all the OEM driver installations and trying to find a match over
the catalog file `wnbd.cat`.
Invoking the clean uninstall will also hard disconnect any online mappings.
Document the usage of the client utility `wnbd-client` to install
and clean uninstall the driver.

Add command line options to install and uninstall the driver

---

driver/debug.c
driver/driver.c
vstudio/driver.vcxproj
vstudio/reinstall.ps1
vstudio/wnbdevents.xml

Add ETW support for the kernelspace.
For now, we define and use a single variable event which reuses
the messages relayed via WnbdLog.
To install and remove the custom events we need to use the utility:
`wevtutil`
To start a trace session one can use:
tracelog -start WNBDEventdrv -guid #FFACC4E7-C115-4FE2-9D3C-80FAE73BAB91 -f WNBDEventdrv.etl
To stop:
tracelog -stop WNBDEventdrv
To display the trace use:
tracerpt WNBDEventdrv.etl
WNBD error and warning messages are automatically displayed inside the default `SYSTEM` channel.

Add etw support

---

include/wnbd.h

Cross-compiling on Linux (as part of the Ceph build) currently fails with:
[ 97%] Building CXX object src/tools/rbd_wnbd/CMakeFiles/rbd-wnbd.dir/rbd_wnbd.cc.obj
In file included from ../ceph/src/tools/rbd_wnbd/wnbd_handler.h:16,
from ../ceph/src/tools/rbd_wnbd/wnbd_handler.cc:16:
../ceph/build.deps/src/wnbd/include/wnbd.h:12:10: fatal error: SetupAPI.h: No such file or directory
12 | #include <SetupAPI.h>
|          ^~~~~~~~~~~~
compilation terminated.
Fix this by changing setupapi.h to lowercase.
Signed-off-by: Mike Latimer <mlatimer@suse.com>

Lowercase SetupAPI.h for cross-compile on Linux

---

README.md
driver/debug.h

We're documenting the logging facilities, but those can be
disabled through driver options.
That being considered, this patch documents the driver options
and the related "wnbd-client" commands.

Document driver options

---

driver/driver.c
driver/scsi_driver_extensions.h
driver/scsi_operation.c
driver/userspace.c
driver/userspace.h
driver/util.c
libwnbd/libwnbd.cpp

We're using the SCSI address when generating connection IDs as well as when handling PNP remove requests. This is prone to race conditions as the same SCSI address may be reused by a different device after an unmap.
We're going to use a counter instead of the address for the connection ID, just as we do for IO request tags. At the same time, we're going to check the device PDO when handling PNP events.

Fix unmap race conditions

---

libwnbd/wnbd_ioctl.cpp

Unmapping a device will spam the log file with a lot of message of the type:
libwnbd.dll!WnbdIoctlSendResponse WARNING Could not send response.
Connection id: 2. Request id: 0. Error: 1168. Error message: Element not found.
Demote the error to debug instead of warning.

libwnbd: Demote WnbdIoctlSendResponse logging

---

include/wnbd.h
include/wnbd_ioctl.h
ksocket_wsk/berkeley.c
ksocket_wsk/ksocket.c
ksocket_wsk/ksocket.h
libwnbd/libwnbd.cpp
libwnbd/wnbd_ioctl.cpp
wnbd-client/client.cpp
wnbd-client/cmd.cpp
wnbd-client/cmd.h
wnbd-client/main.cpp

Fix compiler warnings
A few functions have incorrect annotations, which raises static code
analysis warnings. One of the functions is "DiUninstallDevice", which
is part of the Windows SDK so we can't do anything other than wrap it
with "pragma"s.
At the same time, we have an incorrect "switch" statement, which will
incorrectly count IO errors.
Also, we're disabling the 26812 warning. The wnbd public headers
include enums and we can't use "enum class" since we have to be retain
C compatibility.

Fix compiler warnings

---

driver/driver.c

When receiving IRP_MN_START_DEVICE, we check if the device count
is nonzero. The issue is that this counter is incremented *after*
storport gets notified that a new device has been created.
In some cases, we skip fetching the disk number because of that.
It happens on WS2016 VMs for every attached disk.
We'll drop this unnecessary device counter check.

driver: fix missing disk number

---

get_dependencies.ps1

Most modern websites require TLS 1.2, and older PowerShell versions do not enforce it by default.

Enforce TLS1.2 in PowerShell

---

README.md
appveyor.yml

We're updating the appveyor artifacts to include libwnbd, the
install script as well as the ETW manifest.
While at it, we're adding a link to the Ceph beta MSI, which
includes a WNBD build.

Update appveyor script and readme

---

driver/scsi_operation.c

We have an incorrect overflow check, preventing us from unmapping
the last block of a disk.
This went unnoticed as Windows seems to do a write as a fallback.

driver: fix unmapping last block

---

vstudio/driver.vcxproj

Using the new Windows 11 SDK + WDK (10.0.22000.0), the testing build errors out with:
```
The driver will be test-signed. Driver signing options can be changed from the project properties.
Sign Inputs: C:\workspace\wnbd\vstudio\x64\Debug\wnbd.sys
C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\signtool.exe sign /ph /sha1 "8010D8632A9CC49D4782603AC417B493534C23C0"
SIGNTASK : SignTool error : No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option. [C:\workspace\wnbd\vstudio\driver.vcxproj]
```
Explicitly …

Use explicit SHA256 fd algorithm for driver sign

---

README.md

Document WNBD limitations
We've added a note about the WNBD limitations and possible
workarounds as part of the Ceph documentation.
It's worth adding the same notes to the WNBD readme, especially
considering that some people may use WNBD without Ceph/RBD.
Closes: #61

Document WNBD limitations

---

appveyor.yml
vstudio/driver.vcxproj

Fix Appveyor job
The CI job is currently failing as the signing algorithm is set for "Release" and "Debug" builds but not for the "Analyze" one.
At the same time, the Analyze job is a resource intensive operation which now times out under Appveyor, for which reason we're going to temporarily disable it.
When preparing or reviewing driver changes, we recommend running the static code analysis by invoking the "Analyze" build locally.

Fix Appveyor job

---

README.md
libwnbd/wnbd_ioctl.cpp

Improved error message when the wnbd adapter is unavailable
In some cases, the WNBD adapter may be unavailable after
(re)installing the driver, which may require a host reboot.
In order to improve the user experience, we'll update the error
message accordingly.

Improved error message when the wnbd adapter is unavailable

---

.github/workflows/mirror-main-branch.yaml

Use this GitHub workflow to mirror the default `main` branch to
the old `master` branch until all the references to `main` branch
are updated.

Temporarily mirror main branch

---

Dockerfile/Readme.md
README.md
SubmittingPatches.rst

Commit 9f0d43bf3a63a3e44f65ef2453413d9203eaa71a renamed `wnbd.dll` to `libwnbd.dll`. Clean up stray references to `wnbd.dll`.

documentation: fix libwnbd.dll filename

---

libwnbd/libwnbd.cpp
libwnbd/wnbd_ioctl.cpp

When a device was unmapped, thousands of invalid requests were received by the IO dispatchers, which in turned tried to send responses to the now missing device.
For solving this issue, we now check the status of the WNBD responses that are being sent, stopping the dispatchers if ERROR_NOT_FOUND is received and proceeding with the unmap.
Also, the log messages for WnbdIoctlRemove were changed as follows:
- included a success message for the soft removal option
- when the hard removal faces ERROR_FILE_NOT_FOUND, the log messages states that the device might have already been removed

libwnbd: Unmap invalid requests fix

---

driver/scsi_operation.c
driver/util.c
driver/util.h
driver/wnbd_dispatch.c
include/wnbd.h
include/wnbd_ioctl.h
libwnbd/libwnbd.cpp

Add persistent reservation support
We're making the necessary driver and libwnbd changes so that userspace daemons may receive scsi persistent reservation requests, when advertised as supported.
To keep things simple, we're only defining two libwnbd callbacks: ``PersistInFunc`` and ``PersistOutFunc``. The libwnbd consumers will have to decode the scsi operation parameters and return the expected data.

Add persistent reservation support

---

driver/scsi_operation.c
driver/wnbd.inf
include/wnbd_ioctl.h

Added support for VPD page 0x83, containing an identifier which is compliant with the NAA IEEE Registered Extended format. This is required by the Microsoft Failover Cluster validation tool.
For the same reason, we're changing the bus type from "virtual" to "sas".

VPD 83h page NAA Identifier

---

README.md

Now that wnbd supports persistent reservations, we can update the "limitations" section from the readme.
Note that in case of rbd-wnbd, older Ceph versions do not support this feature.

doc: update limitations

---

driver/nbd_protocol.c
driver/userspace.c
libwnbd/wnbd_ioctl.cpp

driver:
- avoid logging an error when gracefully closing NBD connections
- added missing log message parameter in WnbdCreateConnection, which was causing a crash when mapping NBD images while having INFO logging enabled
- return STATUS_ACCESS_DENIED when failing to connect to nbd servers because of the nbd policy
libwnbd:
- updated the error message for WnbdIoctlCreate, pointing the user to driver and nbd logs

NBD logging improvements

---

driver/driver.c
driver/util.c
driver/util.h

The wnbd driver currently ignores IRP_MN_QUERY_REMOVE_DEVICE calls, expecting the rest of the Windows storage stack to prevent the disk removal if there are pending operations or unflushed data.
As a precaution, we'll add a check at the wnbd driver level, signaling that the disk is not ready to be removed if there are pending requests in our queues.

driver: handle IRP_MN_QUERY_REMOVE_DEVICE

---

libwnbd/libwnbd.cpp

When calling WnbdSetDiskSize, the block count property of the device received as a parameter wasn't being updated before returning. Therefore, while the actual block count of the device was changed, the property of the referenced PWNBD_DISK wasn't properly updated to the new value.

libwnbd: Fixed device block count update on resize

---

libwnbd/libwnbd.cpp

Read and write operations can receive the Force Unit Access flag which bypasses caches.
We'll update the according debug messages, ensuring that the FUA flag is logged.

libwnbd: log FUA flag

---

driver/driver.c

In driver.c, some logs regarding device unmaps were trying to access the value of Device->Properties.InstanceName after the device was being released.
This caused Driver Verifier to report a page fault when the driver's log level was set to 4 (debug).

driver: Fixed some issues found using Driver Verifier

---

.gitignore
driver/userspace.c
include/wnbd_ioctl.h
libwnbd/libwnbd.cpp
packages.config
tests/libwnbd_tests/libwnbd_tests.vcxproj
tests/libwnbd_tests/mock_wnbd_daemon.cc
tests/libwnbd_tests/mock_wnbd_daemon.h
tests/libwnbd_tests/packages.config
tests/libwnbd_tests/pch.cpp
tests/libwnbd_tests/pch.h
tests/libwnbd_tests/request_log.cpp
tests/libwnbd_tests/request_log.h
tests/libwnbd_tests/test.cpp
tests/libwnbd_tests/utils.cpp
tests/libwnbd_tests/utils.h
vstudio/wnbd.sln

Add wnbd tests 
For testing purposes, we're adding a mock WNBD daemon which is
going to record the requests it receives and send predetermined
replies. It's based on our Ceph WnbdHandler.
This commit provides a few relatively simple test cases that:
* map a mock WNBD disk and validate the WnbdShow output
* test invalid wnbd disk parameters
* cover various scenarios:
* cache enabled/disabled
* various sector sizes
* various disk sizes, up to 2PB (we haven't defined a maximum
disk size yet though)
* perform a few simple IO operations
* read, write, flush
* various offsets, including the beginning/end of the disk as well
as invalid offsets, expecting an error
* various IO sizes: one sector and then twice the maximum transfer
size, expecting fragmented operations
* check the returned data as …

Add wnbd tests

---

tests/libwnbd_tests/mock_wnbd_daemon.cc
tests/libwnbd_tests/mock_wnbd_daemon.h
tests/libwnbd_tests/test_disk_actions.cpp

Added tests for removing WNBD disks, covering the following scenarios:
- soft remove w/ & w/o hard remove fallback
- hard remove
- soft removal time-out

tests: Disconnect tests

---

driver/driver.h
driver/scsi_driver_extensions.c
driver/userspace.c
libwnbd/libwnbd.cpp
wnbd-client/cmd.cpp

This PR fixes the following SCSI address issues:
* avoid leaking addresses
* use the device list spinlock when accessing the address bitmap
* specify the right bus when notifying storport about bus changes
* use the right size when allocating the bitmap
* properly handle the addresses without making assumptions about the maximum number of luns and targets

driver: fix scsi addressing

---

driver/scsi_operation.c

When mapping a device, three consecutive info level log messages related to the failure of the WnbdSetModeSense function were being printed. This happend due to two unsupported mode pages, respectively the "Control" (0xAh) and "Informational Exceptions Control" (0x1Ch) mode pages. These two pages are related to task set management and error logging, which we don't support.
In order to make info level logging clearer, the WnbdSetModeSense failure logs have been set as debug level.

driver: Changed WnbdSetModeSense failure log message level to debug

---

README.md
driver/wnbd.inf
include/wnbd.h
libwnbd/utils.cpp
libwnbd/utils.h
libwnbd/wnbd_ioctl.cpp

This PR pins the minimum supported Windows version to 10.0.17763, which is the oldest tested version. The driver will refuse to install on unsupported Windows versions.
We're adding a hard requirement mostly because the driver has been reported to cause boot loops on unsupported Windows versions. For example, the WSK initialization causes a crash on 10.0.14393.

Add Windows version checks

---

Dockerfile/Dockerfile
README.md
driver/driver.c
driver/nbd_dispatch.c
driver/nbd_protocol.c
driver/nbd_protocol.h
driver/scsi_operation.c
driver/userspace.c
vstudio/driver.vcxproj

The CodeQL static analysis tests used for driver certification suggest us to replace the deprecated ExAllocatePoolWithTag function with ExAllocatePoolZero or ExAllocatePool2. The main reason is that those replacements will zero the allocated memory by default.
ExAllocatePool2 is only available on hosts >= 2004, while we intend to support older versions as well. For this reason, we'll use
ExAllocatePoolZero instead.
For Windows versions prior to 2004, we'll also have to define POOL_ZERO_DOWN_LEVEL_SUPPORT and call
ExInitializeDriverRuntime(DrvRtPoolNxOptIn) during driver initialization [1]. Apart from zero-ing the allocated memory, this
also marks it as non-executable by default.
We'll rename the Malloc and NbdMalloc ExAllocatePoolWithTag wrappers to MallocZero and NbdMallocZero to …

Fix codeql static analysis warnings, required for driver certification

---

driver/userspace.c
driver/userspace.h
libwnbd/utils.cpp
tests/libwnbd_tests/mock_wnbd_daemon.cc
tests/libwnbd_tests/test_io.cpp

This change addresses a few static code analysis warnings:
* WnbdSetDiskSize declared in userspace.h
* avoided strcpy
* used const reference instead of unecessary copy
While at it, we'll skip a flaky stats test.

Fix code static analysis warnings

---

driver/wnbd_dispatch.c

Unlike the nbd dispatcher, the wnbd dispatcher doesn't increment the counter after forwarding IO requests.
This change ensures that submitted requets will be tracked accordingly, which is useful for debugging purposes.

driver: track submitted requests

---

driver/driver.c
driver/options.c
driver/userspace.c
include/wnbd.h
include/wnbd_ioctl.h
tests/libwnbd_tests/libwnbd_tests.vcxproj
tests/libwnbd_tests/test_adapter_actions.cpp
tests/libwnbd_tests/utils.cpp
tests/libwnbd_tests/utils.h

The driver certification tests fail if we access absolute registry paths, which means we can't directly use the registry path received by the DriverEntry function.
Instead, we'll have to use "IoOpenDriverRegistryKey" to open the registry key associated with this driver and then use Zw* functions instead of Rtl* when accessing the registry.
We'll go ahead and remove the WNBD_REGISTRY_KEY definition since it no longer applies. Wnbd users are expected to use libwnbd or DeviceIOControl in order to get/set driver settings, for example through wnbd-client.exe.
While at it, we're adding some tests for the driver settings. Those tests uncovered an issue affecting IOCTL_WNBD_GET_DRV_OPT requests, which is being addressed.

driver: avoid absolute registry paths

---

.gitignore
driver/wnbd.inf
vstudio/build_deps.vcxproj
vstudio/driver.vcxproj
vstudio/generate_version_h.ps1

When building the driver, stampinf is called with -v "*", which overrides the .inf version with "hours.minutes.seconds.milliseconds".
For this reason, the Windows device manager will show the wnbd build timestamp instead of the driver version, which can be confusing.
This change will call stampinf.exe explicitly using the wnbd SemVer version.
Since the inf file will be updated every time we do a build, we'll add it to .gitignore.

driver: include semver instead of timestamp in INF

---

driver/userspace.c
driver/util.c

NBD connections are currently affected by "PERSISTENT RESERVATION IN" requests, which get queued despite the fact that NBD doesn't support this operation. Certain Windows operations end up waiting indefinitely for some persistent reservation commands.
This change fixes the persistent reservation support check, ensuring that those operations won't be queued unless supported by the backend.
We'll explicitly clear this flag for NBD connections.

driver: fix persistent reservation checks

---

driver/nbd_protocol.c
driver/userspace.c
driver/util.c
ksocket_wsk/ksocket.c
ksocket_wsk/ksocket.h

According to the MS docs, each successful WskRegister call must be followed by exactly one WskDeregister call with the same registration structure. The same applies to WskCaptureProviderNPI and WskReleaseProviderNPI.
The issue is that we're calling the KsInitialize wrapper for every new nbd connection, however there's a single KsDestroy call in the HwFreeAdapterResources hook.
Another issue is that the KsDestroy call will be performed regardless of the previous KsInitialize status. We'd basically be destroying a structure that wasn't properly initialized. This seems to cause crashes on older Windows hosts that do not provide the WSK API that we're using.
This change fixes WSK initialization and cleanup.
Worth mentioning that we're most likely going to move the nbd client to userspace …

driver: fix wsk initialization

---

driver/options.c

The RtlInitUnicodeString docs [1] suggest us to use the RTL_CONSTANT_STRING macro when initializing UNICODE_STRING structures. There's even the following reference:
UNICODE_STRING RTL_CONSTANT_STRING(
[in]  PCWSTR SourceString
);
However, RTL_CONSTANT_STRING uses sizeof, so it's going to use the size of the pointer instead of the string length.
Visual studio will throw a warning but only for the "Analyze" builds:
C:\workspace\wnbd\driver\options.c(250): warning C28132: Taking
the size of pointer Name:  This will yield the size of a pointer
(4 or 8), not the size of the object pointed to. Dereference the
pointer, or if the size of a pointer was intended, use the
pointer type or (void *) instead.
That being considered, we'll just use RtlInitUnicodeString instead.
Signed-off-by: Lucian …

driver: fix unicode initialization

---

tests/libwnbd_tests/mock_wnbd_daemon.cc
tests/libwnbd_tests/mock_wnbd_daemon.h
tests/libwnbd_tests/test_disk_actions.cpp
tests/libwnbd_tests/test_io.cpp
tests/libwnbd_tests/utils.cpp
tests/libwnbd_tests/utils.h

The number of constructor arguments for MockWnbdDaemon was getting
out of hand, with some arguments only being necessary for one test.
With this commit, the constructor will only receive a pointer to a
WNBD_PROPERTIES structure that will contain all the properties set
accordingly for each test.
In every test, a default WNBD_PROPERTIES structure will be generated
using the GetNewWnbdProps function from utils.cpp, which receives a
reference to a WNBD_PROPERTIES structure, and for any custom
requirements, the values can be modified before calling the Start 
method of the MockWnbdDaemon class.

tests: Drop MockWnbdDaemon excessive constructor params

---

driver/nbd_dispatch.c
driver/scsi_operation.c
driver/util.c
driver/util.h
driver/wnbd_dispatch.c
tests/libwnbd_tests/libwnbd_tests.vcxproj
tests/libwnbd_tests/mock_wnbd_daemon.cc
tests/libwnbd_tests/mock_wnbd_daemon.h
tests/libwnbd_tests/options.cpp
tests/libwnbd_tests/options.h
tests/libwnbd_tests/pch.h
tests/libwnbd_tests/test.cpp
tests/libwnbd_tests/test_io.cpp
tests/libwnbd_tests/test_nbd.cpp

We're adding some tests that exercise the NBD client functionality. The NBD export information can be specified using the following CLI parameters:
* --nbd-export-name
* --nbd-host
* --nbd-port (default: 10809)
If unspecified, the NBD tests will be skipped.
For consistency, we're replacing the WNBD_LOG_LEVEL env variable with a CLI parameter: --log-level.
We'll also address some issues that were brought up by the tests:
* updated srb status in case of nbd errors
* validate IO address on the driver side

Add nbd tests

---

tests/libwnbd_tests/test_disk_actions.cpp
tests/libwnbd_tests/utils.cpp
tests/libwnbd_tests/utils.h

We're adding a new functional test that lists the current WNBD disk connections:
* it starts by creating two mappings
* retrieves the connection list
* ensures that the connection list contains the two expected mappings and validates the connection info
* removes the mappings and verifies that the updated connection list

Add connection list test

---

driver/nbd_protocol.c

Whenever a NBD connection is closed, a warning message will be emitted.
We'll check the actual status code and avoid logging a warning in case of a graceful disconnect.

driver: avoid logging read failures when closing nbd conn

---

tests/libwnbd_tests/test_disk_actions.cpp

One of the tests tries to create mappings with unsupported parameters, expecting a failure. If a mapping does get created, it won't be removed.
This change will ensure that such mappings get cleaned up.

tests: cleanup mappings after failed negative tests

---

README.md
driver/driver.c
driver/nbd_dispatch.c
driver/options.c
driver/options.h
driver/scsi_driver_extensions.c
driver/scsi_driver_extensions.h
driver/scsi_function.c
driver/scsi_function.h
driver/scsi_operation.c
driver/scsi_operation.h
driver/scsi_trace.c
driver/scsi_trace.h
driver/userspace.h
driver/util.c
driver/util.h
driver/wnbd_dispatch.c
include/wnbd.h
include/wnbd_ioctl.h
libwnbd/libwnbd.cpp
libwnbd/libwnbd.def
libwnbd/wnbd_ioctl.cpp
tests/libwnbd_tests/test_adapter_actions.cpp
tests/libwnbd_tests/utils.h
wnbd-client/client.cpp
wnbd-client/cmd.cpp
wnbd-client/cmd.h

Right now, we're limited to 255 requests per LUN and 1000 requests per adapter, which might be insufficient for large workloads.
We're going to make this configurable. Note that in order to be allowed to increase the limit, we need to support extended SRBs. This means that instead of accessing SRBs directly, we'll need to use the DDK helpers, which can handle both standard SRBs (``SCSI_REQUEST_BLOCK``) and extended SRBs (``STORAGE_REQUEST_BLOCK``).
Resetting the adapter is required in order for the new IO limits to be applied. For convenience, we're also adding a command that can be used to hard remove all attachments and then reset the adapter.
Sample:
```
PS C:\> wnbd-client.exe show rbd/test_4g_5
Connection info
...
MaxIOReqPerLun            : 255
MaxIOReqPerAdapter        : 1000
PS …
```

Increase IO limit

---

README.md

When connecting to local NBD servers, caching has to be disabled on the nbd daemon side in order to avoid deadlocks. We'll document this and provide a qemu-storage-daemon example.
Note that this issue does not affect Ceph.
Another way to mitigate it would be to forward LUN resets to the NBD daemon and reestablish the NBD connection. This would still be less than ideal since IO would be stuck for 30s, until Storport issues a reset. It would also require some changes on the driver side (e.g. separate queue for control commands, otherwise the dispatchers might be stuck with IO operations).

Document caching issue with local nbd servers

---

README.md

The Github Action build status badge is broken:
https://github.com/orgs/community/discussions/14980
We're getting the "no status" message, so we'll go ahead and remove it for now so that we won't confuse users.

Drop build status badge

---

.github/workflows/pr-tests.yaml
README.md
driver/options.c
driver/options.h
driver/scsi_driver_extensions.h
driver/scsi_function.c
driver/scsi_operation.c
driver/userspace.c
driver/util.c
driver/util.h
driver/wnbd_dispatch.c
include/wnbd_ioctl.h
wnbd-client/cmd.cpp

Storport resets the lun after hitting request timeouts. However,
it never actually removes the disk. Having a stale disk can be
troublesome, leading to an unresponsive host in certain situations
(e.g. cache deadlocks, hanging persistent reservation
requests, etc).
For this reason, we'll detect stale connections and disconnect
the disk. This feature along with the timeouts are configurable.
By default, we'll consider a connection to be stale if at least one
request older than 15s got aborted and if no IO reply was received
in the last minute.
At the same time, we'll include the following timestamps in the
``wnbd-client.exe stats`` output:
* last received request
* last submitted request
* last received reply

Detect and remove stale connections

---

wnbd-client/cmd.cpp

"wnbd-client stats" now reports a few time counters, such as "TimeSinceLastReceivedReqMs". Those counters have a ~15ms accuracy, so for really short intervals we can end up with a negative value when comparing with the current timestamp:
```
TimeSinceLastReceivedReqMs     : 18446744073709551604
TimeSinceLastSubmittedReqMs    : 18446744073709551604
TimeSinceLastReplyMs           : 18446744073709551604
```
This patch will translate such intervals to 0.

client: properly handle negative time counters

---

README.md

We've recently introduced a few IO timers so we're updating the stats sample accordingly.

Update readme, including IO timers

---

include/wnbd.h
libwnbd/libwnbd.cpp
libwnbd/libwnbd.def
tests/libwnbd_tests/utils.cpp

After mapping a WNBD disk, we're informimg the Storport driver that the bus changed, expecting it to rescan the bus and then expose the disk. This happens asynchronously and usually takes a few milliseconds, however it can take a few seconds under huge load.
WNBD clients need to wait for the disk to become available before being able to use it. For convenience, we'll add a function that performs the necessary polling, waiting for a disk number to be assigned. It optionally opens the disk, ensuring that it's ready.

libwnbd: add WnbdPollDiskNumber function
